configName: SAMD21_IOT_WG_BMI160
folderName: ''
format_version: v1.0
frameworkPath: ../../Microchip/Harmony3
processor: ATSAMD21G18A
projectName: ''
settings:
  PackageFilter: audio;bsp;core;core_apps_sam_d21_da1;csp;csp_apps_sam_d21_da1;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21a\atdf\ATSAMD21G18A.atdf
